apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
  labels:
    app: tasks-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-service
  template:
    metadata:
      labels:
        app: tasks-service
    spec:
      containers:
        - name: tasks-service
          image: tasks_service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8001"
          ports:
            - containerPort: 8001
